### ISSUE TITLE
Enh: Service Classes

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/composer#25]
For the first official release of the Composer module the following needs done beforehand

- [ ] Refactor all task controllers for service usage
- [x] Move `git` commands to new `GitService` class
- [x] Move `composer` commands to new `ComposerService` class
- [ ] Move `grunt` commands to new `GruntService` class
- [ ] Update all required view files
- [ ] Error Handling
